- [Setup a minimal Linode VPS](https://www.pragmaticlinux.com/2020/07/setup-a-minimal-debian-10-buster-server-as-a-linode-vps/)
- [Configure domain with Linode](https://www.pragmaticlinux.com/2020/08/how-to-configure-a-domain-name-for-your-linode-vps/)
- [Install LAMP stack](https://www.pragmaticlinux.com/2020/10/install-a-lamp-stack-on-debian-10-buster/)
